name: Go

on:
  push:
    branches: [ main, 3.x ]
  pull_request:
    branches: [ main, 3.x ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v -o hydra ./...
    
    - name: Test
      run: go test -v ./...